services:
  db:
    build: ./database
    restart: always
  api:
    build: .
    command: /app/blog-api
    environment:
      DATABASE_URL: mongodb://db:27017
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - db
