services:
  db:
    build: ./database
    restart: always
  api:
    build: .
    command: /app/blog-api
    environment:
      ADDR: "0.0.0.0:8080"
      DB_URL: "mongodb://db:27017/go_blog"
    ports:
      - "8080:8080"
    depends_on:
      - db
